version: '3'

services:
  # Sonarr - TV Show Management
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  # Radarr - Movie Management
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  # Jellyseerr - Request Management
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    restart: unless-stopped
    depends_on:
      - jellyfin

  # Jellyfin - Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/mali
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${MEDIA_DIR}:/media
      - /usr/lib/aarch64-linux-gnu/mali:/usr/lib/aarch64-linux-gnu/mali
      - /etc/OpenCL:/etc/OpenCL
    restart: unless-stopped
    privileged: true # Required for hardware acceleration
    devices:
      # Hardware acceleration devices
      - /dev/dri:/dev/dri # Intel/AMD GPU
      - /dev/dma_heap:/dev/dma_heap # Memory management
      - /dev/mali0:/dev/mali0 # ARM Mali GPU
      - /dev/rga:/dev/rga # Rockchip RGA
      - /dev/mpp_service:/dev/mpp_service # Rockchip MPP
      - /dev/iep:/dev/iep # Rockchip IEP
      - /dev/mpp-service:/dev/mpp-service # Rockchip MPP alternative
      - /dev/vpu_service:/dev/vpu_service # Rockchip VPU
      - /dev/vpu-service:/dev/vpu-service # Rockchip VPU alternative
      - /dev/hevc_service:/dev/hevc_service # Rockchip HEVC
      - /dev/hevc-service:/dev/hevc-service # Rockchip HEVC alternative
      - /dev/rkvdec:/dev/rkvdec # Rockchip video decoder
      - /dev/rkvenc:/dev/rkvenc # Rockchip video encoder
      - /dev/vepu:/dev/vepu # Rockchip video encoder
      - /dev/h265e:/dev/h265e # H.265 encoder

  # Transmission - BitTorrent Client
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER:-admin}
      - PASS=${TRANSMISSION_PASS:-adminadmin}
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${DOWNLOADS_DIR}/watch:/watch
    restart: unless-stopped

  # NZBGet - Usenet Downloader
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/nzbget:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

volumes:
  media:
    driver: local

networks:
  default:
    name: media_network
